# -*- coding: utf-8 -*-
"""clust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15d-hZZYy3EjF2uf4n0Zd9D6H67jkIml3
"""

from sklearn.datasets import load_digits

X_digits, y_digits = load_digits(return_X_y=True)

from sklearn.model_selection import train_test_split

x_train , x_test , y_train,y_test=train_test_split(X_digits,y_digits)

from sklearn.linear_model import LogisticRegression

log_reg=LogisticRegression()

x_train



log_reg.fit(x_train,y_train)

log_reg.score(x_test,y_test)

from sklearn.pipeline import Pipeline

from sklearn.cluster import KMeans

pipeline=Pipeline([

      ('kmean',KMeans(n_clusters=50)),
     ('log_reg',LogisticRegression())

])

pipeline.fit(x_train,y_train)

pipeline.score(x_test,y_test)

from sklearn.model_selection import GridSearchCV

param=dict(kmean__n_clusters=range(2,100))

grid_clf=GridSearchCV(pipeline,param_grid=param,cv=3,verbose=2)

grid_clf.fit(x_train,y_train)

grid_clf.best_params_

grid_clf.score(x_test,y_test)

n_labeled=50

log_reg=LogisticRegression()
log_reg.fit(x_train[:n_labeled],y_train[:n_labeled])

log_reg.score(x_test,y_test)

k=50

kmeans=KMeans(n_clusters=k)

X_digit_dist=kmeans.fit_transform(X_digits)

import numpy as np

X_train_dist = kmeans.transform(x_train)
representative_digit_idx=np.argmin(X_train_dist,axis=0)
X_representative_digit  =x_train[representative_digit_idx]

X_representative_digit



import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

for i, image in enumerate(X_representative_digit):
    plt.subplot(5, 10, i + 1)
    plt.imshow(image.reshape(8, 8), cmap="binary")
    plt.axis("off")
    plt.title(i)

plt.tight_layout()
plt.show()

y_representative_digits=np.array([4,8,9,0,5,6,1,2,7,5,9,4,6,1,3,1,1,0,9,7,7,1,6,1,8,3,4,5,4,2,1,4,3,3,0,4,4,5,4,5,1,3,7,5,8,8,6,9,9,4])

log_reg=LogisticRegression()
log_reg.fit(X_representative_digit,y_representative_digits)

log_reg.score(x_test,y_test)

log_reg=LogisticRegression()
log_reg.fit(X_representative_digit,y_representative_digits)

log_reg.score(x_test,y_test)

y_train_propogated=np.empty(len(x_train),dtype=np.int32)

x_train_cluster_labels = kmeans.predict(x_train)
for i in range (k):
  y_train_propogated[x_train_cluster_labels==i]=y_representative_digits[i]

log_reg=LogisticRegression()
log_reg.fit(x_train,y_train_propogated)

log_reg.score(x_test,y_test)

percentile_closest=20

X_cluster_dist=X_digit_dist[np.arange(len(x_train)),x_train_cluster_labels]
for i in range(k):
  in_cluster=(x_train_cluster_labels==i)
  cluster_dist=X_cluster_dist[in_cluster]
  cutoff_distance=np.percentile(cluster_dist,percentile_closest)
  above_cutoff=(X_cluster_dist>cutoff_distance)
  X_cluster_dist[in_cluster & above_cutoff]=-1

partially_propagated=(X_cluster_dist!=-1)
x_train_partially_propagated=x_train[partially_propagated]
y_train_partially_propagated=y_train_propogated[partially_propagated]

log_reg=LogisticRegression()
log_reg.fit(x_train_partially_propagated,y_train_partially_propagated)

log_reg.score(x_test,y_test)

