# -*- coding: utf-8 -*-
"""clust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15d-hZZYy3EjF2uf4n0Zd9D6H67jkIml3
"""

from sklearn.datasets import load_digits

X_digits, y_digits = load_digits(return_X_y=True)

from sklearn.model_selection import train_test_split

x_train , x_test , y_train,y_test=train_test_split(X_digits,y_digits)

from sklearn.linear_model import LogisticRegression

log_reg=LogisticRegression()

x_train



log_reg.fit(x_train,y_train)

log_reg.score(x_test,y_test)

from sklearn.pipeline import Pipeline

from sklearn.cluster import KMeans

pipeline=Pipeline([

      ('kmean',KMeans(n_clusters=50)),
     ('log_reg',LogisticRegression())

])

pipeline.fit(x_train,y_train)

pipeline.score(x_test,y_test)

from sklearn.model_selection import GridSearchCV

param=dict(kmean__n_clusters=range(2,100))

grid_clf=GridSearchCV(pipeline,param_grid=param,cv=3,verbose=2)

grid_clf.fit(x_train,y_train)

grid_clf.best_params_

grid_clf.score(x_test,y_test)

n_labeled=50

log_reg=LogisticRegression()
log_reg.fit(x_train[:n_labeled],y_train[:n_labeled])

log_reg.score(x_test,y_test)

k=50

kmeans=KMeans(n_clusters=k)

X_digit_dist=kmeans.fit_transform(X_digits)

import numpy as np

X_train_dist = kmeans.transform(x_train)
representative_digit_idx=np.argmin(X_train_dist,axis=0)
X_representative_digit  =x_train[representative_digit_idx]

X_representative_digit

y_representative_digits=np.argmax(X_representative_digit,axis=1)

log_reg=LogisticRegression()
log_reg.fit(X_representative_digit,y_representative_digits)

log_reg.score(x_test,y_test)

