# -*- coding: utf-8 -*-
"""DR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCu746C7aE8AdDHZcAwsgq4xckXWaGaZ
"""

from sklearn.datasets import make_swiss_roll

X, y = make_swiss_roll(
    n_samples=1000,    # Number of points
    noise=0.2,         # Add Gaussian noise
    random_state=42    # Reproducibility
)

X

y

X.shape

y.shape

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(18,16))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=y, cmap="Spectral")
plt.show()

from sklearn.decomposition import PCA

pca=PCA(n_components=2, random_state=42,)

X2D=pca.fit_transform(X)

X2D

pca.components_

pca.explained_variance_ratio_

pca1=PCA(n_components=0.95, random_state=42)

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_reduced=pca1.fit_transform(X_train)

X_reduced

from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print(X_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)

print(X_test.shape)   # (10000, 28, 28)
print(y_test.shape)   # (10000,)

import matplotlib.pyplot as plt

plt.imshow(X_train[0], cmap="gray")
plt.title(f"Label: {y_train[0]}")
plt.axis("off")
plt.show()

X_train = X_train.reshape(-1, 28 * 28) / 255.0
X_test = X_test.reshape(-1, 28 * 28) / 255.0

mnist_pca=PCA(n_components=0.95, random_state=42)

mnist_reduced=mnist_pca.fit_transform(X_train)

X_recovered=mnist_pca.inverse_transform(mnist_reduced)

print(mnist_reduced.shape)

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(
    X_train.flatten(),
    X_recovered.flatten()
)

print(mse)

import numpy as np

mse = 0.003349383485008159
rmse = np.sqrt(mse)
print(rmse)

import matplotlib.pyplot as plt

idx = 0

plt.figure(figsize=(6, 3))

plt.subplot(1, 2, 1)
plt.imshow(X_train[idx].reshape(28, 28), cmap="gray")
plt.title("Original")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(X_recovered[idx].reshape(28, 28), cmap="gray")
plt.title("Recovered")
plt.axis("off")

plt.show()

pca_randomized=PCA(n_components=155, svd_solver="randomized", random_state=42)

pca_randomized.fit_transform(X_train)

print(mnist_reduced.shape)
print(pca_randomized.components_.shape)
print(pca_randomized.n_components_)
print(pca_randomized.explained_variance_ratio_.sum())

from sklearn.decomposition import PCA

pca_randomized = PCA(
    n_components=154,
    svd_solver="randomized",
    random_state=42
)

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(18,16))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(X_[:, 0], X[:, 1], X[:, 2], c=y, cmap="Spectral")
plt.show()







randomized_reduced = pca_randomized.fit_transform(X_train)

randomized_reduced.shape

print(pca_randomized.components_.shape)
print(pca_randomized.n_components_)
print(pca_randomized.explained_variance_ratio_.sum())

from sklearn.linear_model import LogisticRegression

model_original = LogisticRegression(max_iter=1000)
model_original.fit(X_train, y_train)

pred_original = model_original.predict(X_test)

X_train_pca = mnist_pca.fit_transform(X_train)
X_test_pca = mnist_pca.transform(X_test)

model_pca = LogisticRegression(max_iter=1000)
model_pca.fit(X_train_pca, y_train)

pred_pca = model_pca.predict(X_test_pca)

changed = (pred_original != pred_pca).sum()
print("Changed predictions:", changed)

percentage = changed / len(y_test) * 100
print(f"Changed: {percentage:.2f}%")

from sklearn.metrics import accuracy_score

print("Original Accuracy:", accuracy_score(y_test, pred_original))
print("PCA Accuracy:", accuracy_score(y_test, pred_pca))

X_train_std = mnist_pca.fit_transform(X_train)
X_test_std = mnist_pca.transform(X_test)

X_train_rand = pca_randomized.fit_transform(X_train)
X_test_rand = pca_randomized.transform(X_test)

model_std = LogisticRegression(max_iter=1000)
model_std.fit(X_train_std, y_train)

model_rand = LogisticRegression(max_iter=1000)
model_rand.fit(X_train_rand, y_train)

pred_std = model_std.predict(X_test_std)
pred_rand = model_rand.predict(X_test_rand)

print("Predictions changed:", (pred_std != pred_rand).sum())

changed = (pred_original != pred_pca)

print("Number of changed predictions:", changed.sum())

import numpy as np

indices = np.where(changed)[0]

print(indices[:20])  # First 20 changed samples

import matplotlib.pyplot as plt
i = indices[0]

print("True Label       :", y_test[i])
print("Original Model   :", pred_original[i])
print("PCA Model        :", pred_pca[i])

import matplotlib.pyplot as plt

plt.imshow(X_test[i].reshape(28, 28), cmap="gray")
plt.title(
    f"True: {y_test[i]}, Original: {pred_original[i]}, PCA: {pred_pca[i]}"
)
plt.axis("off")
plt.show()

from sklearn.decomposition import IncrementalPCA

n_batches = 100
inc_pca = IncrementalPCA(n_components=154)

for x_batch in np.array_split(X_train, n_batches):
    inc_pca.partial_fit(x_batch)

X_reduced = inc_pca.transform(X_train)

X_reduced

from sklearn.decomposition import KernelPCA

rbf_pca = KernelPCA(n_components=2, kernel="rbf", gamma=0.04)
X_reduced = rbf_pca.fit_transform(X)

X_reduced

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(18,16))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(X_reduced[:, 0], X[:, 1], X[:, 2], c=y, cmap="Spectral")
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import  Pipeline
import numpy as np
clf= Pipeline([
    ("kpca",KernelPCA(n_components=2,random_state=42)),
    ("logistic",LogisticRegression(random_state=42))

])


param_grid=[{
    "kpca__gamma":np.linspace(0.03,0.05,10),
    "kpca__kernel":["rbf","sigmoid"]
}]

grid_search=GridSearchCV(clf,param_grid,cv=3)

y_min = y.min()
y_max = y.max()
bins = np.linspace(y_min, y_max, 5) # Create 4 bins, 5 edges
y_discrete = np.digitize(y, bins) - 1 # Make labels 0, 1, 2, 3

grid_search.fit(X, y_discrete)

grid_search.best_params_

rbf_kernel=KernelPCA(n_components=2,kernel='rbf',gamma=0.0433,fit_inverse_transform=True)
X_reduced=rbf_kernel.fit_transform(X)
X_preimage=rbf_kernel.inverse_transform(X_reduced)

from sklearn.metrics import mean_squared_error

mse=mean_squared_error(X,X_preimage)
print(mse)

